name: GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/docs.yml'
      - 'docs/**'
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    defaults:
      run:
        working-directory: docs
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Setup PNPM
        run: corepack enable && corepack prepare --activate

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          check-latest: true
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - run: pnpm build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ github.token }}
          publish_dir: ./website/build
